spring:
  application:
    name: sqlserver
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=demo;integratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 1
  flyway:
    enabled: true
    schemas: demo
    baseline-on-migrate: true
    locations: classpath:db/migration