version: "3.8"
name: spring-boot-sqlserver-demo
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: R00tPassword12!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "1"
          memory: 2G

volumes:
  mssql-data:
