version: '3.8'
name: spring-boot-sqlserver-demo
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1"
    ports:
      - "1433:1433"
    volumes:
      - ./data/sqlserver:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
